http:
  middlewares:
    # Security headers middleware
    security-headers:
      headers:
        stsSeconds: 31536000
        frameOptions: "DENY"
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
    
    # Compression middleware
    gzip-compression:
      compress: {}
    
    # Analytics path stripping
    analytics-stripprefix:
      stripPrefix:
        prefixes:
          - "/.ghost/analytics"
    
    # Rate limiting (optional)
    rate-limit:
      rateLimit:
        burst: 100
        average: 50

  # Global middleware chain for all routes
  middlewares:
    default-chain:
      chain:
        middlewares:
          - security-headers
          - gzip-compression

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"